site_name: Cloudflare Bulk Image Uploader
site_url: https://github.com/alexgQQ/cloudflare-bulk-image-upload
site_author: Alex Grand
site_description: Usage and reference documentation for the cloudflare_image_uploader package
theme:
  name: material
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    logo: material/cloud-upload
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - search.suggest
    - search.highlight

plugins:
  - search
  - tags
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ "cloudflare_image_uploader" ]
          options:
            show_submodules: true
            show_bases: true
            show_root_heading: true
            show_source: false
            annotations_path: brief
            docstring_style: google
  - include-markdown:
      preserve_includer_indent: true
nav:
  - Home: index.md
  - API Reference: reference.md
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: https://github.com/alexgQQ/cloudflare-bulk-image-upload
extra:
  social:
    - icon: material/web
      link: https://alexgrand.dev/
